readme.md
src/config.cpp
src/data/config.js
src/data/home.html
src/input.cpp
src/input.h
src/src.ino
src/web_server.cpp

A handful of fixes
- Some typos that don't matter much
- Fix call to Vcc detection so it works properly
- Fix some unused element IDs in javascript by using them in html: Vcc, amps, flash size (these broke rendering)
- Update energy totals & faults in the main loop rather than only at bootup

Fixes to master

---

src/config.cpp
src/data/config.js
src/data/home.html
src/emoncms.cpp
src/http.cpp
src/input.cpp
src/mqtt.cpp
src/ohm.cpp
src/src.ino
src/web_server.cpp
src/wifi.cpp

So, here's a stab at whitespace fixups.
For the actual code, it was mostly done with
`# indent -i2 -nut -br -brf -ce -npcs`
which means: 
```
2-space indentation
spaces instead of tabs
braces go on line with if
braces go on function definition line
Cuddle else and preceding ‘}’
no space after the function in function calls
```
with some manual cleanup later.
html & javascript was pretty much manual.   There is a tad of non-whitespace change in there too, I guess, for example breaking long lines.
I think it's better, but of course style is a matter of taste, so feel free to take it or leave it.  I recognize that it makes merging patches across the whitespace change really tough, so if now's not the time that's ok too.
Thanks,
-Eric

Whitespace cleanup

---

src/data/config.js
src/data/home.html

Another handful of small things:
- The mqtt page had a couple typos
- The OhmConnect key help is unclear
- Some RAPI commands were missing from the RAPI page
- Display wifi firmware version with other wifi info
- The Safety Checks html used odd intermediate javascript vars, consolidate
- current min/max range is never displayed for the "other" level, so hide it.
See full commit logs for more info.  Basic testing went OK on the system in my garage.  :)

More small fixes

---

.travis.yml
src/debug.h
src/divert.cpp
src/emoncms.cpp
src/emonesp.h
src/input.cpp
src/mqtt.cpp
src/ohm.cpp
src/profile.h
src/src.ino
src/web_server.cpp
src/wifi.cpp

Added some basic profiling code to help identify code that is blocking the CPU and stopping other stuff happening.

Add profiling

---

platformio.ini
src/config.cpp
src/config.h
src/data/config.js
src/data/home.htm
src/data/style.css
src/src.ino
src/web_server.cpp

Changes to implement explicit enabling and disabling of the various services. This resolves #29 and #14. 
This also includes some HTML/CSS improvements;
- Simplify the styling and avoid some of the rendering issues. 
- Tabs are now managed partly by JS. This allows the tab to be persisted across reloads.
I would have separated these, but they are kind of dependant as the original tabs style precluded the use of label, which in turn is needed for the enable/disable check boxes.

Service enable/disable

---

src/config.cpp
src/data/config.js
src/data/home.htm
src/debug.h
src/src.ino
src/web_server.cpp
src/wifi.cpp

Various changes to help free up memory
- Store constant strings in flash (program) memory rather that dynamic memory
- Don't keep WiFi scan results hanging around
- Don't keep 'EEPROM' content hanging around in memory
There are a few additional changes (in the code but disabled and/or commented out) that can be made but these depend on newer API's in the Git version of the ESP8266 Arduino Core.

Memory optimisation

---

platformio.ini
src/config.cpp
src/data/config.js
src/data/home.htm
src/debug.h
src/src.ino
src/web_server.cpp
src/wifi.cpp

A bunch of bug fixes and tweaks made while investigating (but not totally resolving) #41.
- Various improvements to debug
- Tweaks for Visual Studio Code compatibility
- Few more memory savings
- WiFi scan fixes
- Fix crash when loading the update page

Various fixes discovered while debugging #41

---

src/RapiSender.cpp
src/RapiSender.h
src/input.cpp
src/input.h
src/src.ino
src/web_server.cpp
src/wifi.cpp

Here's a first stab at using @lincomatic 's RapiSender class.
It has some slight modifications, first to make the coding style consistent w/ this project, and a small change to allow a request of the original response string for the RAPI tab.  (I'll probably revert that and just iterate over the tokens in the response...)
Note that this puts the serial delay in the main loop, but playing with it a little, it seems ok.  See what you think.
It could also use some smarts to decide when it's OK to turn on the sequence ID feature.
Related to that, how far back is this project supposed to be compatible w/ OpenEVS version and/or protocol version?  It might need a little care in that respect as well.
Anyway, seems like a decent first cut, let me know what you think.

rapi sender class test

---

src/data/config.js
src/data/home.htm
src/data/wifi_portal.htm
src/data/wifi_portal.js
src/debug.h
src/divert.cpp
src/src.ino
src/web_server.cpp

Added a cut down version of the UI that can only setup the WiFi, will hopefully lead to easier setup and should lessen the effect of #41

WiFi Setup Portal

---

src/mqtt.cpp

The Solar divert logic was using = rather than == when checking the topic, fixes #53.
Also changed to use RapiSender.

Fix for RAPI via MQTT

---

src/data/config.js
src/data/home.htm
src/data/style.css

Added the UI changes as described in #52;
- The text information in the html page should be changed to info pop out boxes
- The Solar PV divert buttons (eco / normal) should be moved to the main OpenEVSEtab and the Mode button should be removed

Solar Divert UI

---

src/divert.cpp
src/src.ino

Implemented several of the issues in #52
- Only adjust charging current up to the maximum already set in the OpenEVSE
- The RAPI commands sent by the divert function should be changed to use the rapi sender class which will add the checksum and be more robust.
Implemented #59,  event the state through MQTT on change
Plus some additional improvements;
- General improvements to code readability (hopefully)
- Fixed getting the current ammeter reading

Solar divert updates

---

src/data/openevse.js

Fixed not handling the RAPI checksum.
Still need to actually check the checksum

Fix for running with latest Dev firmware

---

src/data/config.js
src/data/home.htm
src/data/style.css
src/web_server.cpp

Fixed display of divertmode

---

src/data/config.js
src/data/home.htm
src/data/style.css
src/input.cpp
src/input.h
src/web_server.cpp

Changes to implement a simple status UI as described in #66.

Simple Status UI

---

src/data/config.js
src/data/home.htm
src/data/openevse.js
src/data/wifi_portal.htm
src/debug.h
src/lcd.cpp
src/lcd.h
src/ota.cpp
src/src.ino
src/web_server.cpp
src/wifi.cpp

A bunch of changes loosely centred around resolving issues fixed in the latest OpenEVSE dev firmware
- Fixed Enable/Disable of vent required
- Fixed Enable/Disable of temp monitoring (subject to ongoing discussion on lincomatic/open_evse#62)
- Fixed delay timer not being persisted (#69), including limited support without the new firmware.
- Fixed corruption issues of LCD messages and generally improved the display of LCD messages
- displaying the AP and IP details no does not block for 5 seconds 
- Both HTTP and ArduinoOTA update display the % complete
- Firmware version displayed on boot
- Support for update of SPIFFS via HTTP upload, #7 
- General bug fixes

Dev firmware updates

---

src/data/config.js
src/data/home.htm
src/divert.cpp
src/divert.h
src/event.h
src/mqtt.cpp
src/openevse.h
src/src.ino
src/web_server.cpp

Switch back to Normal mode on disconnecting the car from the charger

---

src/wifi.cpp

This will clear out WiFi config saved in the ESP config. Fixes #86

Small fix to allow upgrade from V1.

---

.travis.yml
scripts/ci_arduino.sh
scripts/ci_platformio.sh
src/src.ino

Fix for compiling in Arduino IDE, fixes #94 . Was due to Arduino adding its magic in the wrong place. Also added building with the Arduino IDE to the Travis CI builds to help maintain Arduino IDE compatibility

Arduino IDE fix

---

src/input.cpp

allow volts to be sent to feed if valid

add volts to feed

---

.gitignore
Vagrantfile
simulator/example-openevse-apache.conf
simulator/openevse.service

Quick and dirty Vagrant box to help testing the Simulator in HTTPS mode, with Apache acting s a reverse proxy.

Simulator Vagrant box

---

src/html/style.css

show am/pm in some browsers
Fixes #168

chaged time field width

---

src/web_server.cpp

Fix misspelling.

---

platformio.ini
readme.md
src/app_config_mode.h

addresses https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/279 and other build errors I was seeing in platformio
only tested with platformio cli build

update dependencies and some readme adjustments
